### ISSUE TITLE
Line number is wrong in hint of exercise #1, Move Semantics

### ISSUE THREAD

**Issue by horrorvacui** [carols10cents/rustlings#17]
The line number is stated as 8 as to where the error occurs. The actual line is 10. I don't know if the line number is relative to the start of the function or expressed based on actual line numbering. Either case, the line numbering in the hint needs to be clearified or corrected.

**Comment by toddthomas** [comment]
I created a pull request containing this fix: https://github.com/carols10cents/rustlings/pull/19.

**Comment by carols10cents** [comment]
Merged in #19!! Thank you again :) :) :) :tada:
