### ISSUE TITLE
the link to function4 is actually a link to the solution of function3

### ISSUE THREAD

**Issue by iqualfragile** [carols10cents/rustlings#30]

**Comment by carols10cents** [comment]
Hm, I'm not seeing this-- when I click on function3, I see:

<img width="880" alt="function3" src="https://cloud.githubusercontent.com/assets/193874/12870522/05ccd56e-cd17-11e5-9424-905a726dee81.png">

And when I click on function 4, I see:

<img width="873" alt="function4" src="https://cloud.githubusercontent.com/assets/193874/12870523/1353a712-cd17-11e5-859a-50a247b6d938.png">

So I'm not sure what happened-- could you try it again?

One guess I have is that play.rust-lang.org saves the last code you ran in your browser's localStorage, so if something went wrong with loading function4, it might have been your function3 solution that loaded instead-- but i'm not sure why function4 wouldn't have loaded!

**Comment by iqualfragile** [comment]
Turns out it was the firefox addon noscript blocking some, but not all of the stuff being loaded (because it suspects an xss attack, sometimes the code=<stuffs> seems to look like javascript)
Thanks for this project, btw, was quite helpful for me to get started with rust.

**Comment by carols10cents** [comment]
Hm, interesting! This will be useful to know if other people run into this problem in the future. I'm glad you enjoyed it!!
