### ISSUE TITLE
Rust Playground can not run the code

### ISSUE THREAD

**Issue by voddan** [carols10cents/rustlings#33]
Rust Playground compiles, but does *not* run examples!

**To reproduce:**
1) I follow a link like https://play.rust-lang.org/?code=%2F%2F+Make+me+compile%21+Scroll+down+for+hints+%3A%29%0A%0Afn+main%28%29+%7B%0A++++x+%3D+5%3B%0A++++println%21%28%22x+has+the+value+%7B%7D%22%2C+x%29%3B%0A%7D%0A%0A%0A%0A%0A%0A%0A%0A%0A%0A%0A%0A%0A%0A%0A%0A%0A%0A%0A%0A%0A%0A%0A%0A%0A%0A%0A%0A%0A%0A%0A%0A%0A%0A%2F%2F+Hint%3A+The+declaration+on+line+4+is+missing+a+keyword+that+is+needed+in+Rust%0A%2F%2F+to+create+a+new+variable+binding.%0A

2) Compiler works and tells you to fix an issue
3) Fix the example
4) Hit "RUN" 
5) error 101:

```thread '<main>' panicked at 'called `Option::unwrap()` on a `None` value', ../src/libcore/option.rs:367
playpen: application terminated with error code 101```

**Environment:**
Mac OS X, Google Chrome

**Comment by jdm** [comment]
That link gives me this output when I press "Run":
```


<anon>:4:5: 4:6 error: unresolved name `x` [E0425]
<anon>:4     x = 5;
             ^
<anon>:4:5: 4:6 help: see the detailed explanation for E0425
<anon>:5:36: 5:37 error: unresolved name `x` [E0425]
<anon>:5     println!("x has the value {}", x);
                                            ^
<std macros>:2:25: 2:56 note: in this expansion of format_args!
<std macros>:3:1: 3:54 note: in this expansion of print! (defined in <std macros>)
<anon>:5:5: 5:39 note: in this expansion of println! (defined in <std macros>)
<anon>:5:36: 5:37 help: see the detailed explanation for E0425
error: aborting due to 2 previous errors
playpen: application terminated with error code 101

Compilation failed.
```
I'm using Mac OS X, Firefox Nightly

**Comment by jdm** [comment]
I think there's an issue with the playground environment right now, because all code I try to run exhibits the same problem. This has already been filed as https://github.com/rust-lang/rust-playpen/issues/178.

**Comment by carols10cents** [comment]
Yep, seems to be fixed now! The above steps work for me. Maybe I should run my own playground??? ;)

Thank you for the great bug report!! :bug:
