### ISSUE TITLE
strings2 output is a bit misleading

### ISSUE THREAD

**Issue by glenjamin** [carols10cents/rustlings#41]
I got the correct answer, and the program compiled - but the output of the program said:
```
Nope, that's not it.
```

Which led me to spend 10 minutes trying to figure out what I'd got wrong - before realising that this was the correct result!

**Comment by carols10cents** [comment]
Ew you're totally right! That is confusing! Reworking it now :)

**Comment by carols10cents** [comment]
Just pushed an update, would love to know what you think!! Thank you for the feedback!!!

**Comment by glenjamin** [comment]
Looks great, thanks!
