### ISSUE TITLE
if1.rs silently succeeds

### ISSUE THREAD

**Issue by dvberkel** [carols10cents/rustlings#46]
The `if1.rs` rustling does not provide any feedback that you succeeded when you correctly implemented a solution.

Even though I understood why, it was a bit jarring to not seeing any form of output. Maybe especially so because I worked on `if1.rs` right after the test rustlings which give nice confirmation of their success and failure.

There are a few options to change the behavior of `if1.rs` if the current behaviour is deemed problematic. The ones I could think of are listed below.

1. **Make `if1.rs` a test**. *pro*: This provides instant standardized feedback for both correct and incorrect implementations. *con*: It could muddle the lesson about `if.
2. **print some output**. *pro*: user has confirmation if they are correct. *con*: It also could muddle the lesson about `if`.

I am willing an able to make changes to `if1.rs` and send a pull request for any improvements that are suggested. I am just opening this issue to discuss if it is a problem at all, and if it is a problem how to improve `if1.rs`.

**Comment by carols10cents** [comment]
I'd love to make the experience less jarring! I think option 1, making this into a test or two, would be best, especially since it comes after the test exercises as you mentioned.

I'd love a pull request if you have time!! Thank you so much for the feedback!! ❤️

**Comment by dvberkel** [comment]
Thank you so much for taking the time to create rustlings. I would love to contribute and give something back.

I will clone the repository and work on option 1. You should expect a pull request soon.
