### ISSUE TITLE
programming error in exercise (not one you're supposed to correct!)

### ISSUE THREAD

**Issue by chriscamacho** [carols10cents/rustlings#50]
in the second primitive types exercise if

```
let your_character = '#';
```

then it says its 

```
Alphabetical!
Neither alphabetic nor numeric!
```

**Comment by booyaa** [comment]
Hi! The 1st line is from the `my_first_initial` test. The 2nd line refers to `your_char`, '#' is neither alphabetic or numeric so this is correct.

**Comment by mwilli20** [comment]
I think this issue can be closed. @chriscamacho just misread the print out. There is no issue with the exercise.
