### ISSUE TITLE
Update documentation link in all "Relevant chapter in The Rust Programming Language" hyperlinks

### ISSUE THREAD

**Issue by DineshMv** [carols10cents/rustlings#60]
Rust Language is updated now. So, all the links must be updated according to [second edition](https://doc.rust-lang.org/stable/book/second-edition/). 

PS: @carols10cents I can work on this issue, if you are ok with it. :)

**Comment by carols10cents** [comment]
That would be great!!!

**Comment by carols10cents** [comment]
Fixed by #62!!
