### ISSUE TITLE
Add Filename to source code

### ISSUE THREAD

**Issue by robertlugg** [carols10cents/rustlings#66]
I really like the interactive session that I can get to from the main page, but I often forget which one I am working on.  Having its name in the code would be convenient.  I wouldn't mind pushing a change if you agree that this would be a good idea.

**Comment by carols10cents** [comment]
Sure!

**Comment by robertlugg** [comment]
I realize that the README.md has the samples embedded in it.  Is this auto-generated or do you know how I would update it?

**Comment by carols10cents** [comment]
It's sort of auto generated-- I run [this prlinks tool](https://github.com/btbytes/prlink) (I believe it's `cargo install`able) and then put the markdown it generates in README.md and commit that manually. I suppose that could be scripted via travis or similar, but I haven't gotten around to it yet.

Let me know if that works or if you'd like me to take care of the README part!

**Comment by robertlugg** [comment]
Hi @carols10cents, I created a pull request (still not an expert in github).  If it is acceptable, can you integrate it in?

**Comment by carols10cents** [comment]
Fixed by #68! Thank you!!
