### ISSUE TITLE
References to line numbers now wrong, slightly

### ISSUE THREAD

**Issue by maxim-lian** [carols10cents/rustlings#69]
I think as a result of https://github.com/carols10cents/rustlings/pull/68, where 'line 10' was referenced should now be 'line 11'

**Comment by carols10cents** [comment]
Oops :(

**Comment by carols10cents** [comment]
I think I fixed all the line number references; please reopen and let me know which exercise is wrong exactly if you see any more!! ❤️

**Comment by maxim-lian** [comment]
Nice, thanks - so fast!
