### ISSUE TITLE
Solutions and exercises from the rust book

### ISSUE THREAD

**Issue by fleimgruber** [carols10cents/rustlings#75]
I am working through https://github.com/rust-lang/book and it's exercises.  I figured the exercises plus solutions could be put into this repo.  Or is there already another place?

If the exercises and solutions are to be put here, should they be filed under a `rust_book` subdir or be filed in the existing categories?

**Comment by carols10cents** [comment]
I think the book deserves to have its exercises and solutions in its own supplemental project. See some discussions in issues on the book repo like:

- https://github.com/rust-lang/book/issues/822
- https://github.com/rust-lang/book/issues/337

Also, the book's exercises start with a different premise than rustlings' do-- the book exercises don't start with broken code to fix like all the other rustling exercises.

Great thought though!
